name: Ethyrial
version: "${version}"
main: io.github.tootertutor.ethyrial.EthyrialPlugin
api-version: "1.21"
load: STARTUP
authors: [TooterTutor]
description: Magic System for Minecraft
commands:
  ethyrial:
    description: Main command for Ethyrial
    usage: /ethyrial <subcommand>
    aliases: [ems]
    permission: ethyrial.command

permissions:
  ethyrial.command:
    description: Allows the player to use ethyrial commands
    default: op
  ethyrial.reload:
    description: Allows the player to reload various aspects of the plugin
    default: op
  ethyrial.admin:
    description: Allows the player to use admin commands
    default: op
  ethyrial.update.notify:
    description: Allows the player to receive update notifications
    default: op

  ethyrial.spell.upload:
    description: Allows the player to upload spells to the server
    default: true
