name : Ethyrial
version : '1.0'
main : io.github.tootertutor.ethyrial.Ethyrial
api-version : '1.21'
load : STARTUP
authors : [ TooterTutor ]
description : Magic System for Minecraft
commands:
  ethyrial:
    description: Ethyrial Magic System
    usage: /ethyrial
    aliases: [ems]
    permission: ethyrial.command
    permission-message: You do not have permission to use this command.

permissions:
  ethyrial.*:
    description: Grants access to all Ethyrial commands
    children:
      ethyrial.command: true
      ethyrial.spell.*: true
  ethyrial.command:
    description: Grants access to the base Ethyrial command
    default: op
  ethyrial.give:
    description: Gives a plugin item to the player
    default: op